#!/bin/bash
#SBATCH --job-name=eval_tests
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=alec.wills@stonybrook.edu
#SBATCH --output=eval.txt
#SBATCH --ntasks-per-node=1
#SBATCH --nodes=4
#SBATCH --time=48:00:00
#SBATCH -p long-40core


cd $HOME
source .bashrc
source /gpfs/projects/FernandezGroup/Alec/miniconda3/etc/profile.d/conda.sh
conda init bash
conda activate rsrch
cd /gpfs/scratch/awills/swxcd/eval/test_subset_ps2/01

for dir in MODEL_MGGA_e*/; do cd $dir; 
python ~/dpyscfl/scripts/eval.py --type MGGA --xc SCAN \
 --refpath /gpfs/scratch/awills/swxcd/aegis/test_subset_ps2/01 \ 
 --reftraj subat_ref.traj --modelpath /gpfs/scratch/awills/swxcd/eval/xcdset/01/$dir/ \
 --writeeach preds --writepred --maxcycle 250 --atomization --gridlevel 5 --forceUKS \
 --gridlevel 5 2>&1 | tee eval.out; cd ../; done;
