#!/bin/bash
#SBATCH --job-name=pts_18og_40c
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=alec.wills@stonybrook.edu
#SBATCH --output=subat.txt
#SBATCH --ntasks-per-node=1
#SBATCH --nodes=2
#SBATCH --time=48:00:00
#SBATCH -p long-40core

cd $HOME
source .bashrc
source /gpfs/projects/FernandezGroup/Alec/miniconda3/etc/profile.d/conda.sh

conda init bash
conda activate rsrch

cd /gpfs/scratch/awills/swxcd/train/test_subset_ps2/18_ogr

python /gpfs/home/awills/ogdpyscf/scripts/train.py \
--pretrain_loc /gpfs/home/awills/dpyscfl/models/pretrained/scan \
--type MGGA --datapath /gpfs/scratch/awills/swxcd/data/test_subset_ps2/12_og \
--reftraj /gpfs/scratch/awills/swxcd/aegis/test_subset_ps2/09/subat_ref.traj \
--targetdir /gpfs/scratch/awills/swxcd/eval/test_subset_ps2/18_ogr \
--logpath . --passthrough --hnorm --print_names \
--print_stdout 2>&1 | tee log.out
