#!/bin/bash
#SBATCH --job-name=pts_10_prep
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=alec.wills@stonybrook.edu
#SBATCH --output=subat.txt
#SBATCH --ntasks-per-node=40
#SBATCH --nodes=4
#SBATCH --time=48:00:00
#SBATCH -p long-40core

cd $HOME
source .bashrc
source /gpfs/projects/FernandezGroup/Alec/miniconda3/etc/profile.d/conda.sh

conda init bash
conda activate rsrch

cd /gpfs/scratch/awills/swxcd/data/test_subset_ps2/10

python ~/dpyscfl/scripts/prep_data.py . SCAN ./subat_ref.traj --forcepol --mingridlevel 5 --ref_path /home/awills/Documents/Research/swxcd/aegis/test_subset_ps2/07 --dfit