#!/bin/bash
#SBATCH --job-name=pts_12
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=alec.wills@stonybrook.edu
#SBATCH --output=subat.txt
#SBATCH --ntasks-per-node=1
#SBATCH --nodes=2
#SBATCH --time=168:00:00
#SBATCH -p extended-96core

cd $HOME
source .bashrc
source /gpfs/projects/FernandezGroup/Alec/miniconda3/etc/profile.d/conda.sh

conda init bash
conda activate rsrch

cd /gpfs/scratch/awills/swxcd/train/test_subset_ps2/12

python /gpfs/home/awills/dpyscfl/scripts/train.py \
--pretrain_loc /gpfs/home/awills/dpyscfl/models/pretrained/scan \
--type MGGA --datapath /gpfs/scratch/awills/swxcd/data/test_subset_ps2/10 \
--reftraj /gpfs/scratch/awills/swxcd/aegis/test_subset_ps2/07/subat_ref.traj \
--targetdir /gpfs/scratch/awills/swxcd/eval/test_subset_ps2/12 \
 --noxcdiffpop --logpath . --passthrough --hnorm
